---
title: "Reproducible Surveys"
format: html
---

## load libraries
```{r}
#| warning: false
#| message: false
library(qualtRics)
library(tidyr)
library(knitr)
library(ggplot2)
library(kableExtra)
library(dplyr)
```

## Connect to Qualtrics API

```{r}
#qualtrics_api_credentials(api_key = "Zzuvz4t36VkB5akSB8W3Dryg5YgZ9lowoc3JEfEN", 
                          #base_url = "ucsb.co1.qualtrics.com", 
                          #install = TRUE, overwrite = T) #install the API save to environment and it will be read in again
# if render this remove this chunck of code first, API key is like a password
```

## Get all surveys

```{r}
surveys <- all_surveys() #gets all surveys in the qualtrics account
```

## Saving suvey ID

```{r}
#save into an object
i <-which(surveys$name == "Survey for Data Science Training") #assigning value to object i, that will save the position for where target survey belongs in surveys table
i #get value of 1, because it is first in table

id <- surveys$id[i] #getting id for survey in position of 'i'

```

## List of questions

```{r}
questions <- survey_questions(id)

kable(questions) %>% 
  kable_styling()

```


## Getting survey results

```{r}
survey_results <- fetch_survey(id) #fetch survey from saved id
```


## Cleaning Results

### Question 2

```{r}
#use tidyverse and dplyr to clean data
q2 <- survey_results %>% 
  select(Q2) %>% 
  group_by(Q2) %>% 
  summarize(n = n()) #creates tally of each response

kable(q2, col.names = c("How long have you been programming?",
                        "Number of Responses")) %>% 
  kable_styling()
```


### Question 3

```{r}
#multiple choice with 'other' option
q3 <- survey_results %>% 
  select(Q3) %>% 
  group_by(Q3) %>% #want to group by each option in Q3
  summarize(n = n())

ggplot(q3,
       aes(x = Q3, y = n))+
  geom_col()+
  labs(x = "What language do you currently use most frequently?")+
  theme_bw()

```


Free text

```{r}
q3_text <- survey_results %>% 
  select(Q3_7_TEXT) %>% 
  drop_na()

kable(q3_text, col.names = "Other Responses to 'What language do you currently use most frequently?'") %>% 
  kable_styling()

```

### Question 4

```{r}
q4 <- survey_results %>% 
  select(Q4) %>% 
  rename("What data science tool or language are you most excited to learn next?" = Q4) %>% #renames column
  drop_na()

kable(q4) %>% 
  kable_styling()
```






